name: Merge PR

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge on "merge" label
    runs-on: ubuntu-latest
    if: github.event.label.name == 'merge'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
